### ISSUE TITLE
Unhandled rejection ValidationFailedError: Validation Failed

### ISSUE THREAD

**Issue by AlexanderKozhevin** [seegno/authy-client#36]
I tried the simplest example
```javascript
const Client = require('authy-client').Client;
const client = new Client({ key: 'QmuGGTF2h1QZ0SxSo3cFn7dEwIBspMyH' });

client.registerUser({
  countryCode: '+7',
  email: 'hey@alex-polymath.com',
  phone: '9629134867'
}).then(function(response) {
  return response.user.id;
}).then(function(authyId) {
  return client.requestSms({ authyId: authyId });
}).then(function(response) {
  console.log(`SMS requested to ${response.cellphone}`);
});
~    
```

And got this:
```
Unhandled rejection ValidationFailedError: Validation Failed
    at validate (/root/demo/node_modules/authy-client/dist/src/validator.js:74:11)
    at _bluebird2.default.try (/root/demo/node_modules/authy-client/dist/src/client.js:636:31)
    at tryCatcher (/root/demo/node_modules/bluebird/js/release/util.js:16:23)
    at Function.Promise.attempt.Promise.try (/root/demo/node_modules/bluebird/js/release/method.js:39:29)
    at Client.registerUser (/root/demo/node_modules/authy-client/dist/src/client.js:621:34)
    at Object.<anonymous> (/root/demo/index.js:4:8)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:390:7)
    at startup (bootstrap_node.js:150:9)
    at bootstrap_node.js:505:3
```

I met this problem here  - https://github.com/AuthySE/Authy-demo
I followed the guidelines and tried to register. But I'm getting exactly the same error.

**Comment by AlexanderKozhevin** [comment]
Never mind, I'm just stupid 😄 
I used numbers instead of letters.
